services:
  backend:
    build: .
    ports:
      - "80:5000"
  sqlServer:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - sql_data:/var/lib/mysql
    ports:
      - "1433:1433"
    environment:
      NAME: "SigmaChat"
      MSSQL_SA_PASSWORD: "JHVHjhvh!"
      ACCEPT_EULA: "Y"

volumes:
  sql_data:
