services:
  backend:
    build: .
    ports:
      - "80:5000"
  sqlServer:
    image: "postgres"
    volumes:
      - sql_data:/var/lib/mysql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=JHVHjhvh!
      - POSTGRES_USER=sa
      - POSTGRES_DB=SigmaChatDb

volumes:
  sql_data:
