services:
  backend:
    build: .
    ports:
      - "5000:80"
    networks:
      - sigmaChat
  sqlServer:
    image: "postgres"
    volumes:
      - sql_data:/var/lib/mysql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=JHVHjhvh!
      - POSTGRES_USER=sa
      - POSTGRES_DB=SigmaChatDb
    networks:
      - sigmaChat
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: azurite
    restart: always

    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./azurite:/workspace
    env_file:
      - ./azurite.env

volumes:
  sql_data:

networks:
  sigmaChat:
    name: sigmaChat
