on:
  push:
    branches:
      - feature/cicd
  pull_request:
    branches:
      - feature/cicd

env:
  IMAGE_NAME: sigmaproductions/sigmachatserver

jobs:
  build:
    runs-on: [self-hosted, build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure appsettings.json
      env:
        appsettings: ${{ secrets.appsettings }}
      run: |
        echo "$appsettings" > appsettings.json && cat appsettings.json
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${IMAGE_NAME}
    - name: Publish the Docker image
      run: docker push ${IMAGE_NAME}:$(date +%s)
  deploy:
    runs-on: [self-hosted, zdechlak]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: dziala
      run: echo 'dziala'
      
