on:
  push:
    branches:
      - feature/cicd
  pull_request:
    branches:
      - feature/cicd
jobs:
  build:
    runs-on: [self-hosted, build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure appsettings.json
      env:
        appsettings: ${{ secrets.appsettings }}
      run: |
        echo "$appsettings" > appsettings.json

      
